apiVersion: v1
kind: Service
metadata:
  name: jogo-adivinhacao-backend-service
  namespace: ms  # O mesmo namespace do Deployment
spec:
  selector:
    app: microservico  # Seleciona os Pods com o rótulo app: microservico
  ports:
    - protocol: TCP
      port: 80          # Porta exposta pelo Service
      targetPort: 5000  # Porta no Pod (containerPort)
  type: ClusterIP       # Tipo de serviço: ClusterIP (padrão)
