apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ms
spec:
  selector:
    service: microservico
  ports:
    - protocol: TCP
      port: 80  # Porta exposta pelo serviço
      targetPort: 80  # Porta no container do frontend
  type: ClusterIP  # O NGINX vai se comunicar com o frontend via ClusterIP
