apiVersion: v1
kind: Service
metadata:
  name: jogo-adivinhacao-frontend-service
  namespace: ms
spec:
  selector:
    service: microservico
  ports:
    - protocol: TCP
      port: 80  # Porta exposta externamente
      targetPort: 80  # Porta no container (NGINX)
      nodePort: 30080  # Porta no nó (ajuste conforme necessário)
  type: NodePort 
