apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ms  # Certifique-se de que o namespace seja o mesmo do backend
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
